### PR TITLE
move Doxyfile & Doxyfile.developer to doc folder

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by philburk** [comment]
When this is merged, I will also need to update the scripts that generate the autodocs on the server. And, yes, those should be in the repo.

**Review by philburk — APPROVED** [review]
I am generally in favor of moving files out of the top folder because it is cluttered.
Alternatively, these files could go in a "scripts" folder.

**Comment by RossBencina** [comment]
I don't get why you would move these, they control documentation generation for the whole source tree, not just the doc folder.

**Comment by Be-ing** [comment]
Oh, I didn't realize that. I'll close this then.

**Pull request closed without merging**
