### PR TITLE
Remove scons

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by RossBencina** [comment]
This should remove all of the scons files. For example, the following files also need to be removed.

```
/SConstruct
/src/SConscript
```

Possibly there are also other `SConstruct` and `SConscript` files elsewhere. I have not done an exhaustive search.

**Comment by philburk** [comment]
There is an Issue #259 that says scons build was not working in 2016.

**Comment by Be-ing** [comment]
> This should remove all of the scons files.

Good catch, fixed.

**Comment by Be-ing** [comment]
ping

**Comment by philburk** [comment]
I see that the MSVC build is failing.  I assume that is unrelated because I doubt that it uses scons.

**Comment by philburk** [comment]
All tests just passed!

**Review by philburk — APPROVED** [review]

**Pull request merged**
