### PR TITLE
Bump version to 19.7.0

### PR DESCRIPTION
**Pull request by philburk**

### CODE REVIEW

**Comment by RossBencina** [comment]
Phil, I notice that your PRs are based off of branches added to the main repository. Is there a reason why you are not submitting PRs from branches in your personal account? That would be more usual. It's just that with your current method you are creating a bunch of branches in the main repo.

**Comment by MichalPetryka** [comment]
> Phil, I notice that your PRs are based off of branches added to the main repository. Is there a reason why you are not submitting PRs from branches in your personal account? That would be more usual. It's just that with your current method you are creating a bunch of branches in the main repo.

I think this PR might have been made using GitHubs Edit, which creates a branch on the current repository if you have permission to do so instead of using a fork.

**Comment by philburk** [comment]
@MichalPetryka - I tried making changes from my own fork. But I was constantly getting unrelated commits tangled up in my PRs. I tried various techniques and always had trouble. I never have that problem when I work on the main repo. So, in order to make progress, I switched back. This is the way that I work on my other repos as well.

I delete my branches when I merge the changes.

**Comment by philburk** [comment]
Do NOT merge until right before we tag the 19.7 release.

**Comment by xasopheno** [comment]
🥇 Thanks for putting together a release! Exciting. First release since 2016. Wow. 🥇

**Review by RossBencina — APPROVED** [review]

**Comment by Be-ing** [comment]
What remains to be done for the release? I think just #504 and #503?

**Comment by philburk** [comment]
> What remains to be done for the release?

You can track progress for Milestone 19.7 at:
https://github.com/PortAudio/portaudio/milestone/9

**Comment by w4mmp** [comment]
Hello,
Will this release support Pulse Audio?
Regards,
Ron

**Comment by Be-ing** [comment]
No, the PulseAudio branch #336 still has unresolved issues. PulseAudio will be obsoleted by PipeWire soon though and #504 ensures that PortAudio will work with PipeWire via the JACK API.

**Comment by w4mmp** [comment]
And is PipeWire (whatever that is) supported on the RPi 4B running Raspbian OS?

73,
Ron / W4MMP

**Comment by Be-ing** [comment]
You'd have to ask the Debian/Raspbian maintainers that.

**Comment by w4mmp** [comment]
OK, I just checked and Debian Buster does support it. I have no idea if the official Raspbian OS will support it but the Raspberry foundation generally follows Debian. We shall see. I'm glad I did not spend any significant time on Pulse Audio.

73,
Ron / W4MMP

**Comment by illuusio** [comment]
I think Official Raspberry OS is switching to Pulseaudio over ALSA.

**Comment by w4mmp** [comment]
> 
> 
> I think Official Raspberry OS is switching to Pulseaudio over ALSA.

Yes, Pulse Audio is the official sound server/manager supplied by Raspberry O.S.   I  know Pulse Audio has experienced problems in the past and a few problems now, but with the Raspberry Foundation now officially supplying it,  I think support will be better (squeaky wheel type of thing).    Which why I was happy to hear that Portaudio was going to support the Pulse Audio API.  But that is no longer the case.

**Comment by philburk** [comment]
> Which why I was happy to hear that Portaudio was going to support the Pulse Audio API. But that is no longer the case.

PulseAudio is not ready for the stable 19.7 release. But  Ross and I hope it can be merged after 19.7 is released. PipeWire will not be available on all platforms and some folks will still want to compile in the PulseAudio support.

If you want to know what is going into 19.7 take a look at the [V19.7 milestone](https://github.com/PortAudio/portaudio/milestone/9).

**Comment by illuusio** [comment]
@philburk yes it's not ready for prime-time yet better postpone to 19.8

**Comment by kunapuli23** [comment]
Looking forward to release 19.7 to address issues with BugSur, please provide updated timeline. thanks.

**Comment by Be-ing** [comment]
I think #503 and #504 should be included in this release.

**Comment by philburk** [comment]
Thanks for the suggestion. #504 is too complex and still being reviewed.
But #503 looks OK for inclusion in 19.7. We will tag RC1, merge #503 and post an RC2 this weekend.

**Pull request merged**
