### PR TITLE
Whitespace cleanup in src

### PR DESCRIPTION
**Pull request by MichalPetryka**
Automatically cleaned up whitespaces in src in preparation for #394:
Tabs were converted to spaces using `find ./ -iname '*.c' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;` for .c, ,h and .cpp.
Lines endings were trimmed and doubled empty lines at file ends removed with my private reformat utility.

### CODE REVIEW

**Review by philburk — CHANGES_REQUESTED** [review]
The reformatting looks great.

But I am concerned about the mingw-include files. They seem to be copies of third party files and it might be better to preserve them as is. Then we can detect when they change upstream. Ross, what do you think?

**Comment by MichalPetryka** [comment]
> The reformatting looks great.
> 
> But I am concerned about the mingw-include files. They seem to be copies of third party files and it might be better to preserve them as is. Then we can detect when they change upstream. Ross, what do you think?

Yeah, I just reformatted all and noticed them while chekcing the changes. I can revert them to original if you want, just wanted to hear what you say.

**Comment by RossBencina** [comment]
I would prefer if you could coordinate with me on this @MichalPetryka . I'm happy to have help, but I'm already in the process of fixing the remaining stuff.  My process is to fix all problems in the file until it passes my chacking script (and my script has evolved slightly since the version currently on GitHub).

The big problem is that we need to avoid stomping on other active PRs. I think the best way to do that is to deal with one host API at a time (one per PR, only submit PR when there are no active PRs on same host API).

I am explicitly ignoring problems with the mingw files and iasiothiscallresolver.h. You can see the files that still need to be fixed listed under "SUMMARY" here

https://github.com/PortAudio/portaudio/issues/398

The mac files have many more problems than you've fixed. If you look at the files you will see that most of the indenting is based on 3-spaces = 1 tab, and uses spaces.

**Comment by MichalPetryka** [comment]
Yeah, that's alright, should I split this up then or wait for your changes?

**Comment by MichalPetryka** [comment]
Also, what about #458 ?

**Comment by RossBencina** [comment]
I have created a ticket for coordinating whitespace issues: #474 please let's continue discussion there.

@MichalPetryka Please give me a few days to try to use your work (this PR) as the basis for breaking this into separate PRs for each remaining host API.

**Comment by RossBencina** [comment]
FYI this PR does not actually address all of the whitespace issues that the script checks for:

```
F:\PortAudio\MichalPetryka-portaudio>git branch
  master
* whitespace-src

F:\PortAudio\MichalPetryka-portaudio>py -3 whitelint.tmp.py

(showing only relevant output)

SUMMARY
=======
error: src\hostapi\alsa\pa_linux_alsa.c (has-bad-indenting)
error: src\hostapi\coreaudio\pa_mac_core.c (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_blocking.c (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_old.c (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_utilities.c (has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\wasapi\pa_win_wasapi.c (has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\wdmks\pa_win_wdmks.c (has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_blocking.h (has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_internal.h (has-tabs, has-bad-indenting, has-trailing-whitespace)
error: src\hostapi\coreaudio\pa_mac_core_utilities.h (has-trailing-whitespace)
```

`bad-indenting` means non-multiple of 4 in non-exceptional circumstances.

**Comment by MichalPetryka** [comment]
This PR doesn't fix non 4 indents, but all trailing whitespaces should already be removed, could you give a line number with a remaining one as an example?

**Comment by RossBencina** [comment]
Partially superseded by #477, #476, #475

**Comment by RossBencina** [comment]
@MichalPetryka here are a few examples, but there are many more:

In `pa_win_wdmks.c`:
```
error: src\hostapi\wdmks\pa_win_wdmks.c(30) trailing whitespace:
b'* The text above constitutes the entire PortAudio license; however, '
error: src\hostapi\wdmks\pa_win_wdmks.c(35) trailing whitespace:
b'* they can be incorporated into the canonical version. It is also '
error: src\hostapi\wdmks\pa_win_wdmks.c(36) trailing whitespace:
b'* requested that these non-binding requests be included along with the '
error: src\hostapi\wdmks\pa_win_wdmks.c(232) trailing whitespace:
b'* an arbitrarily large number */ '
error: src\hostapi\wdmks\pa_win_wdmks.c(374) trailing whitespace:
b'    unsigned            lastPosition; '
error: src\hostapi\wdmks\pa_win_wdmks.c(417) trailing whitespace:
b'struct __PaProcessThreadInfo '
error: src\hostapi\wdmks\pa_win_wdmks.c(5950) trailing whitespace:
b'    if ((result = PreparePinsForStart(&info)) != paNoError) '
error: src\hostapi\wdmks\pa_win_wdmks.c(6031) trailing whitespace:
b'        if (wait == WAIT_FAILED) '
error: src\hostapi\wdmks\pa_win_wdmks.c(6064) trailing whitespace:
b'        /* Since we can mix capture/render devices between WaveCyclic, WaveRT polled and WaveRT notification (3x3 combinations), '
error: src\hostapi\wdmks\pa_win_wdmks.c(6523) trailing whitespace:
b'        /* Bogus event, reset! This is to handle the behavior of this USB mic: http://shop.xtz.se/measurement-system/microphone-to-dirac-live-room-correction-suite '
```

In `pa_win_wdmks.c`:

```
error: src\hostapi\wasapi\pa_win_wasapi.c(57) trailing whitespace:
b'// Fallback from Event to the Polling method in case if latency is higher than 21.33ms, as it allows to use '
error: src\hostapi\wasapi\pa_win_wasapi.c(59) trailing whitespace:
b'// Note: Some USB DAC drivers are buggy when Polling method is forced in Exclusive mode, audio output becomes '
error: src\hostapi\wasapi\pa_win_wasapi.c(60) trailing whitespace:
b'//       unstable with a lot of interruptions, therefore this define is optional. The default behavior is to '
error: src\hostapi\wasapi\pa_win_wasapi.c(111) trailing whitespace:
b' '
error: src\hostapi\wasapi\pa_win_wasapi.c(124) trailing whitespace:
b'    '
error: src\hostapi\wasapi\pa_win_wasapi.c(184) trailing whitespace:
b'    '
error: src\hostapi\wasapi\pa_win_wasapi.c(187) trailing whitespace:
b'    #endif    '
error: src\hostapi\wasapi\pa_win_wasapi.c(188) trailing whitespace:
b'    '
error: src\hostapi\wasapi\pa_win_wasapi.c(195) trailing whitespace:
b'    #endif '
error: src\hostapi\wasapi\pa_win_wasapi.c(216) trailing whitespace:
b'    {    '
error: src\hostapi\wdmks\pa_win_wdmks.c(4034) trailing whitespace:
b'                inputChannelCount, '
error: src\hostapi\wdmks\pa_win_wdmks.c(4130) trailing whitespace:
b'            outputChannelCount, '
error: src\hostapi\wdmks\pa_win_wdmks.c(4146) trailing whitespace:
b'                outputChannelCount, '
error: src\hostapi\wdmks\pa_win_wdmks.c(4200) trailing whitespace:
b'static void ResetStreamEvents(PaWinWdmStream* stream) '
error: src\hostapi\wdmks\pa_win_wdmks.c(4224) trailing whitespace:
b'static void CloseStreamEvents(PaWinWdmStream* stream) '
error: src\hostapi\wdmks\pa_win_wdmks.c(4509) trailing whitespace:
b'                    channelsToProbe, '
error: src\hostapi\wdmks\pa_win_wdmks.c(4526) trailing whitespace:
b'                        channelsToProbe, '
```

**Comment by RossBencina** [comment]
@MichalPetryka In any case, I've fixed the alsa, wdmks and wasapi ones. Please could you review these tickets: #477, #476, #475

**Comment by MichalPetryka** [comment]
@RossBencina a quick look over the git diff shows that the first of your examples is already fixed on my branch, something must be wrong with either your code or git checked out some files incorrectly.
image

**Pull request closed without merging**
