### PR TITLE
Clean up whitespace in src/hostapi/coreaudio in preparation for .editorconfig.

### PR DESCRIPTION
**Pull request by RossBencina**
Convert tabs to 4 spaces. Indent by 4 spaces. Strip trailing whitespace. Ensure EOL at EOF.

### CODE REVIEW

**Comment by RossBencina** [comment]
This is a further manual cleanup of the automatic astyle cleanup in #485. supersedes #485

**Review by philburk — APPROVED** [review]
This looks really great. Alignment is nice.
I tested building on Mac 11.1, Passes.

**Comment by MichalPetryka** [comment]
1. Is it intentional that the `pa_mac_core_old.c` was not fixed?
2. `pa_mac_core_blocking.c` and `pa_mac_core_utilities.c` have 2 newlines at the end of file

**Comment by philburk** [comment]
> Is it intentional that the pa_mac_core_old.c was not fixed?

Yes. That file has now been deleted.

> pa_mac_core_blocking.c and pa_mac_core_utilities.c have 2 newlines at the end of file

Yes, luckily most compilers will accept that.

**Comment by MichalPetryka** [comment]
> Yes, some compilers will warn if there are zero EOLs at the end but two is OK.

Even if they aren't incorrect, they're useless bloat like whitespaces at line endings.

**Comment by philburk** [comment]
>  they're useless bloat like whitespaces at line endings.

True. But releasing a stable 19.7 is a higher priority. We wanted to clean up the indentation because that has more impact and was preventing us from merging the .editorconfig patch. We can fix the extra line after 19.7.

**Pull request merged**
