### PR TITLE
Fixed compiling on linux with mingw

### PR DESCRIPTION
**Pull request by oleg68**
I tried to cross-compile PortAudio with mingw on linux and I received several errors. The reason is

1. src/hostapi/wasapi/mingw-include/functiondiscoverykeys.h

    ```
    #include <FunctionDiscoveryKeys_devpkey.h>
    ```

   but this file has a name in lowercase. It is ignored when compiling on windows but causes an error on linux.

2. There are a lot of "undefined pthread_t" errors in src/hostapi/jack/pa_jack.c because `pthread.h` was not included.

This PR fixes these issues. After this PA can be cross-compiled successfully.

### CODE REVIEW

**Comment by Be-ing** [comment]
The #include has already been fixed in the master branch: 5abfef28cc5d58abdec14ff8746c35d5220b5985

**Comment by Be-ing** [comment]
Regarding the case sensitivity of the file name, I am wondering if it would be better to change the `#include` rather than renaming the file?

```
❯ rg -i functiondiscovery
src/hostapi/wasapi/mingw-include/functiondiscoverykeys_devpkey.h
6:#ifndef _INC_FUNCTIONDISCOVERYKEYS
7:#define _INC_FUNCTIONDISCOVERYKEYS
13:#endif /* _INC_FUNCTIONDISCOVERYKEYS */

src/hostapi/wasapi/mingw-include/functiondiscoverykeys.h
11:#include <FunctionDiscoveryKeys_devpkey.h>

src/hostapi/wasapi/pa_win_wasapi.c
84:    #include <functiondiscoverykeys_devpkey.h>
86:    #include <functiondiscoverykeys.h>
210:    #include <functiondiscoverykeys.h>
```

**Comment by oleg68** [comment]
> The #include has already been fixed in the master branch: [5abfef2](https://github.com/PortAudio/portaudio/commit/5abfef28cc5d58abdec14ff8746c35d5220b5985) There are also other fixes in the master branch for building the JACK backend with MinGW (as well as MSVC).

Yes, I've made a cherry-pick of this change. When I try to merge this branch to the master locally, git doesn't show any difference in this file. I don't know why Github displays them.

**Comment by oleg68** [comment]
> Regarding the case sensitivity of the file name, I am wondering if it would be better to change the `#include` rather than renaming the file?

I've changed it in the way you suggested.

**Comment by oleg68** [comment]
> The #include has already been fixed in the master branch: [5abfef2]There are also other fixes in the master branch for building the JACK backend with MinGW (as well as MSVC).

I'm waiting for the next release of PA, then I'll take the new release.

**Comment by Be-ing** [comment]
Please do an interactive rebase to remove the first two commits from the branch. It doesn't make much sense to merge a commit reverting a commit which already exists in the master branch then cherry pick it back.

>  When I try to merge this branch to the master locally, git doesn't show any difference in this file. I don't know why Github displays them.

Are you trying to merge to an outdated local master branch instead of the upstream master branch from the remote? I personally discourage people from having local master branches (unless you have push access upstream) to avoid this confusion.

**Comment by oleg68** [comment]
@Be-ing I've created a separate PR #660 instead of this one

**Pull request closed without merging**
