### PR TITLE
Upgrade Python 2 code to Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Print is a function in Python 3.  https://docs.python.org/3/whatsnew/3.0.html

### CODE REVIEW

**Comment by RossBencina** [comment]
Maybe best to add `from __future__ import print_function` to avoid gratuitously breaking Python 2 support.

**Comment by cclauss** [comment]
These changes to NOT break Python 2.

**Comment by cclauss** [comment]
macOS no longer ships with Python.

**Review by RossBencina — APPROVED** [review]

**Comment by RossBencina** [comment]
Thank you!

**Pull request merged**
