### PR TITLE
pa_mac_core.c: add missing definition to fix build on older systems

### PR DESCRIPTION
**Pull request by ra1nb0w**
thanks to @kencu

### CODE REVIEW

**Comment by ra1nb0w** [comment]
ping

**Review by philburk — APPROVED** [review]

**Comment by ra1nb0w** [comment]
thank you. FYI: now it works fine on the new Apple M1 (arm64).

**Comment by Be-ing** [comment]
@ra1nb0w can you please clarify what build system you used that worked on M1? Autotools or CMake? Can you test #489? We need someone with M1 hardware to confirm it works.

**Comment by ra1nb0w** [comment]
Ops. Sorry. Wrong comment, I messed up. These fix make build available on system less than 10.6 that doesn't have the define.
At macports we are using autotools. I don't have an M1 yet; probably in a few days I can test it if can wait..

**Pull request merged**
