### PR TITLE
More relaxed behavior with sample rate mismatch during groping

### PR DESCRIPTION
**Pull request by hoene**
solved https://github.com/PortAudio/portaudio/issues/431

### CODE REVIEW

**Comment by philburk** [comment]
I will try to verify this on a Raspberry Pi and on an Ubuntu VM. I have a HiFiBerry DAC.

**Comment by RossBencina** [comment]
@hoene Could you explain what this change does functionally please? I don't understand how it has a different effect from the old code.

**Comment by hoene** [comment]
@RossBencina 
The Hifiberry Pro supports two clock sources, one for 44100 and one for 48000.

Somehow, portaudio, the kernel, or somebody else remembers, which operational mode was selected last time I have run aplay.

Then, when I switch the sampling rate with aplay, portaudio first tests, which sampling rate would be supported. However, during this "groping" the clock source of the Hifiberry is not correctly switched (indeed, during this probing the Hifiberry device driver is not even called). 

My change does not fix this problem. However, it relaxes the grobing function so that even slightly wrong sampling rates are accepted (e.g. 44100 vs. 48000).

**Review by philburk — APPROVED** [review]
I tried to reproduce the bug on an RPi4 using a HiFiBerry Dac+.
I could not reproduce the bug. Probably because it is not the same PRO board.

But I applied this patch and nothing seemed to break.

**Comment by philburk** [comment]
@RossBencina - Are you OK if I merge this?

**Comment by RossBencina** [comment]
> My change does not fix this problem. However, it relaxes the grobing function so that even slightly wrong sampling rates are accepted (e.g. 44100 vs. 48000).

I would not call 44100 vs. 48000 "slightly wrong" these are definitely distinct sample rates and should not be automatically interchanged/substituted.

**Comment by RossBencina** [comment]
> Merge remote-tracking branch 'origin/master' into fix-hifiberry-dacan

as a rule, please don't include merge nodes in pull requests. if necessary, rebase your branch onto current master

**Comment by Be-ing** [comment]
> as a rule, please don't include merge nodes in pull requests. if necessary, rebase your branch onto current master

It would help to document this in a CONTRIBUTING.md file in the root of the repository. Every project has different preferences about this.

**Comment by MichalPetryka** [comment]
> > Merge remote-tracking branch 'origin/master' into fix-hifiberry-dacan
> 
> as a rule, please don't include merge nodes in pull requests. if necessary, rebase your branch onto current master

With small PRs like this one using the `Squash and merge` option deals with them, but with bigger ones  rebasing is better if you want to keep them in multiple commits.

**Comment by trentp-igor** [comment]
> I would not call 44100 vs. 48000 "slightly wrong" these are definitely distinct sample rates and should not be automatically interchanged/substituted.

Indeed, it would be completely wrong to silently substitute 48 kHz when 44.1 KHz is requested.

However, I believe the way this code is supposed to work is that it only requests a sample rate approximately near 44.1k.  The hardware is supposed to set the closest rate it can do, which could be off by any amount.  One must query actual rate afterward to know 44.1 vs 48 vs anything else, and PA does do this correctly.  It should work as "set rate near 44.1", "return rate 48", "default rate is 48 kHz".

It looks like a bug in this hardware driver that it fails rather than return the closest rate.  It may be easier to work around this by hacking portaudio instead of fixing driver, but this leaves driver broken for anything which is not portaudio.

**Comment by philburk** [comment]
I am concerned about coercing paInvalidSampleRate to paNoError. It might mask problems on other devices.
Maybe SetApproximateSampleRate() should be modified.
Or we should just try to get them to fix the driver.
I am reluctant to risk a regression in PortAudio just for a workaround for a buggy driver.
Maybe we could check the device ID and make the workaround conditional.

**Comment by RossBencina** [comment]
I don't think this particular change is an acceptable workaround, given that it effects a wide reaching change to behavior. Possibly some more specific fix would be acceptable. (e.g. changing `SetApproximateSampleRate` to accept buggy sample rate changes only on hifiberry hardware).

I'm closing this now, please free to propose an alternate fix.

**Pull request closed without merging**
