### PR TITLE
Update def files for #340

### PR DESCRIPTION
**Pull request by MichalPetryka**
PaWasapi_SetDefaultInterfaceId being renamed in #340 caused the project to error out when building with Visual Studio

### CODE REVIEW

**Comment by RossBencina** [comment]
Was `PaWasapi_SetDefaultInterfaceId` renamed to `PaWasapiWinrt_SetDefaultDeviceId` ?

**Comment by dmitrykos** [comment]
Yes, it was renamed and 'Winrt' was added additionally to the name for purpose to denote that this API is used exclusivity for WinRT/UWP platform. Updating def file was missed, I am sorry for that.

**Comment by dmitrykos** [comment]
In addition to `PaWasapiWinrt_SetDefaultDeviceId` another function `PaWasapiWinrt_PopulateDeviceList` needs to be added into the `portaudio.def` file, @MichalPetryka could you please add it too into the proposed change?

**Comment by RossBencina** [comment]
@dmitrykos  did you see my other fix: https://github.com/PortAudio/portaudio/pull/363 ?

**Comment by MichalPetryka** [comment]
Made the order there reflect the one in the header, not sure if that broke anything since I never used .def files before

**Comment by RossBencina** [comment]
@MichalPetryka Please don't change the number of existing symbols. Once published the numbers should not change.

**Comment by MichalPetryka** [comment]
Sorry, changed it back

**Comment by RossBencina** [comment]
@MichalPetryka You can discuss __declspec here: https://github.com/PortAudio/portaudio/issues/285 My current opinion is that we are stuck with def files because making the necessary changes to support __declspec in portaudio.h is too painful, and if we remove .def we will break all clients that are depending on ordinals.

**Comment by dmitrykos** [comment]
> @dmitrykos did you see my other fix: #363 ?

Sorry I overlooked it, replied in the thread.

The change in the DEF file is ok.

**Review by dmitrykos — APPROVED** [review]

**Pull request merged**
