### PR TITLE
remove index.html

### PR DESCRIPTION
**Pull request by Be-ing**
This file does not belong in a code repository.

### CODE REVIEW

**Review by philburk — APPROVED** [review]
The information in this file is obsolete.
The README.md file replaces this file.

**Comment by Be-ing** [comment]
What are your criteria for merging PRs? Do both you and @RossBencina need to approve every little change? If so, that will slow down development.

**Review by RossBencina — APPROVED** [review]

**Comment by philburk** [comment]
Yes, Ross and I both need to approve any non-trivial changes. We have found that discussing the changes really helps. Development speed is not our highest priority.

**Comment by Be-ing** [comment]
> Yes, Ross and I both need to approve any non-trivial changes. We have found that discussing the changes really helps. Development speed is not our highest priority.

I suggest to explicitly document this in a CONTRIBUTING.md file in the top of the repository so contributors know what to expect.

**Pull request merged**
