### PR TITLE
cmake: Use GNUInstallDirs

### PR DESCRIPTION
**Pull request by kraj**
Helps install cmakefiles in right libdir

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by Be-ing** [comment]
Duplicate of #589 and #461

**Comment by RossBencina** [comment]
@Be-ing please confirm that this was done in #461 and that we can now close it.

**Comment by Be-ing** [comment]
Yes #461 uses GNUInstallDirs.

**Comment by RossBencina** [comment]
Closing as already done in #461. Please create a new PR if there is any further action required on this.

**Pull request closed without merging**
