### PR TITLE
fix JACK host API build for MSVC and MinGW

### PR DESCRIPTION
**Pull request by Be-ing**
based on #461

### CODE REVIEW

**Comment by Be-ing** [comment]
My [pull request](https://github.com/microsoft/vcpkg/pull/19270) to update the jack2 port in vcpkg and install its pkgconfig file was merged so I switched this to using upstream vcpkg instead of my branch.

**Comment by Chum4k3r** [comment]
I do believe all testing and little commits to do oneline changes to your PR should be made on your fork, before doing the PR. You are spamming and flooding commit emails.

**Comment by Be-ing** [comment]
Unfortunately I cannot do that because the CMake build jobs do not run on GitHub Actions in my fork. Maybe that will be resolved when #461 is merged. I am guessing that is related to GitHub Action's protections for preventing abuse by cryptocurrency miners.

**Comment by Be-ing** [comment]
That should not be an issue anymore because I think this PR is done. I switched macOS and and Ubuntu to installing JACK from vcpkg for consistency. Fortunately the [run-vcpkg](https://github.com/lukka/run-vcpkg) makes it convenient to cache both the vcpkg binary and the packages vcpkg builds.

**Comment by RossBencina** [comment]
It seems to me that this includes some great pthread-related changes to `src/hostapi/jack/pa_jack.c` that should be in a separate PR. Could we make that change first and separately please?

**Comment by Be-ing** [comment]
IMO that is pointless busywork considering I already neatly split the changes into separate commits with descriptive commit messages explaining why the changes were made, but sure. I'll make separate PRs.

**Comment by Be-ing** [comment]
> Unfortunately I cannot do that because the CMake build jobs do not run on GitHub Actions in my fork.

Fixed in #629.

**Comment by RossBencina** [comment]
Waiting for `src/hostapi/jack/pa_jack.c` changes to be removed from this PR.

**Comment by Be-ing** [comment]
I already did that: #626, #627, #628.

**Comment by philburk** [comment]
@Be-ing - Thanks for creating #626, #627, #628
I notice the changes are still in this PR for pa_jack.c.
I assume the plan is to merge #626, #627, #628 and then rebase this change on top of them.
Then the changes for pa_jack.c will fall off.

**Comment by Be-ing** [comment]
>  I assume the plan is to merge #626, #627, #628 and then rebase this change on top of them.

Yes. I cannot test this without those commits in the branch.

**Pull request merged**
