### PR TITLE
Fixed a case-sensitive include

### PR DESCRIPTION
**Pull request by oleg68**
This PR fixed cross-compiling compiling on linux with mingw

### CODE REVIEW

**Comment by RossBencina** [comment]
@dmitrykos is this the correct fix, or should the file be renamed to have mixed case?

**Comment by philburk** [comment]
The file in PortAudio is all lower case.

**Review by Be-ing — APPROVED** [review]
Ubuntu build failures look like unrelated intermittent network error

**Comment by philburk** [comment]
The CI failures were fixed by #665
@oleg68 - You may want to rebase on the latest top of tree.

**Comment by oleg68** [comment]
> The CI failures were fixed by #665 @oleg68 - You may want to rebase on the latest top of tree.

Done

**Comment by RossBencina** [comment]
@dmitrykos it's a small change but we'd like you to confirm whether the correct fix should be to change the include statement or the target file's name. I think it's probably important for the file name to match case with the system version, but I do not know for sure since it seems like many of these include files have had their case changed over time.

**Review by dmitrykos — APPROVED** [review]
The fix is ok. In the current Windows SDK (my version - 10.0.19041.0) this file has low-case name.

**Comment by dmitrykos** [comment]
@RossBencina the PR is correct because according to my Windows SDK lookup this filename is in low-case now. In the past it was like in our sources but now not anymore.

**Pull request merged**
