### PR TITLE
replace Carbon with CoreFoundation and CoreServices

### PR DESCRIPTION
**Pull request by jmelas**
This PR is part of issue #218 .
It removes Carbon dependency and replaces it with CoreFoundation and CoreServices frameworks.

### CODE REVIEW

**Comment by Be-ing** [comment]
I'm amused by your branch name :laughing:

**Comment by philburk** [comment]
Test on Mac

**Review by RossBencina — APPROVED** [review]
I approve this provisionally -- based on us getting some third parties to confirm that these work (both the ./configure and cmake).

**Comment by Be-ing** [comment]
I will test with Mixxx using #461 and downloading the dylib artifact from GitHub Actions.

**Comment by Be-ing** [comment]
I tested on macOS 10.13 and it works. :heavy_check_mark:

**Comment by philburk** [comment]
I tested with cmake and configure on SDK 11.1 on Big Sur and they both compiled.

**Pull request merged**
