### PR TITLE
alsa: Fix building on BSD

### PR DESCRIPTION
**Pull request by alarixnia**
If alsalib is installed this causes a compilation failure :x

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for opening this PR. This looks pretty hacky but for the single specific line of code where PortAudio uses ESTRPIPE it seems like a reasonable workaround. I am unsure if this should be merged upstream; I don't think upstream libraries and applications should have to compensate for ALSA reimplementations' incompleteness. I think it would be better to define this symbol in BSDs' alsalib reimplementations. Would that be feasible?

**Comment by alarixnia** [comment]
The alsalib is not a reimplementation, but the same one used on Linux, outputting to an OSS-compatible device. I think the ESTRPIPE definition is needed because it's usually provided by Linux kernel headers.

**Comment by Be-ing** [comment]
Okay. Please add a comment above the #ifndef explaining that.

**Comment by Be-ing** [comment]
Come to think of it, I have a better idea how to resolve this. Instead of fudging an alias for a missing symbol to define it as another symbol that does exist, let's guard the code that uses the symbol:

```
    if( res == -EPIPE || res == -ESTRPIPE )
    {
        *xrun = 1;
    }
   // ESTRPIPE is provided by the Linux kernel but not available on BSDs which support alsalib
#ifdef ESTRPIPE
   else if (res == -ESTRPIPE)
   {
       *xrun = 1;
   }
#endif
    else
    {
        ENSURE_( res, paUnanticipatedHostError );
    }
```

**Comment by Be-ing** [comment]
Related pull request in libsndfile: https://github.com/libsndfile/libsndfile/pull/775

**Comment by philburk** [comment]
Be-ing's solution is nice. But I notice libsndfile uses

    #if defined ESTRPIPE && ESTRPIPE != EPIPE

Do we need that extra check to avoid compiler warnings when EPIPE==ESTRPIPE.

**Comment by Be-ing** [comment]
@philburk can you approve the GitHub Actions jobs for this new contributor? The code looks good to me now but let's check that CI still passes before merging.

**Pull request merged**
