### PR TITLE
Add the install interface to CMakeLists.txt

### PR DESCRIPTION
**Pull request by Nemirtingas**

### CODE REVIEW

**Comment by RossBencina** [comment]
@dechamps could you give your opinion on this please?

**Comment by jcelerier** [comment]
as an outsider this looks good and will make it easier to use portaudio from other cmake-based buildsystems, right now one had to add the include paths manually, this will make it unnecessary - just calling `target_link_libraries(my_app PRIVATE portaudio)` will also forward the correct include paths, etc

**Comment by dechamps** [comment]
@RossBencina I think this should be merged; it makes sense, is consistent with CMake best practices, and can help consumer projects locate PortAudio when configuring. I have verified that it doesn't seem to break anything.

**Comment by Nemirtingas** [comment]
Thanks, that will help vcpkg by removing a patch for your library.

**Pull request merged**
