### PR TITLE
Run MSBuild MSVC project CI for pull requests

### PR DESCRIPTION
**Pull request by RossBencina**

### CODE REVIEW

**Review by philburk — APPROVED** [review]
I am not very familiar with yaml.
But I do not see any problems.

**Comment by MichalPetryka** [comment]
Why not run it on all branches, not just master?

**Comment by Be-ing** [comment]
I think it would be better to remove the MSVC project files: #434

**Comment by RossBencina** [comment]
@MichalPetryka I don't know how to make it run on all branches. Why would we want to run on non-current branches? and how would I configure it to do that?

**Comment by MichalPetryka** [comment]
Making it like this should make it work on all branches, can be useful when working on a branch to see if it compiles correctly without a PR to master.
```
on: [push, pull_request]
```

**Comment by RossBencina** [comment]
@MichalPetryka  I have changed it to the suggested:

`on: [push, pull_request]`

But I am not sure that is different from my previous proposal

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

Which is what the other file c-cpp.yml is using.

**Pull request merged**
