### PR TITLE
Use GNUInstallDirs module instead of hard-coded path

### PR DESCRIPTION
**Pull request by h3ndrk**
This PR uses [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) instead of hard-coded paths (e.g. `${CMAKE_INSTALL_LIBDIR}/...` instead of `lib/...`, etc.). The hard-coded paths do not work e.g. in Yocto because when generating multilib images the library directory is `/usr/lib64`. It is best practice to therefore use [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) which detects most common environments and provides the correct paths.

This PR depends on #583.

### CODE REVIEW

**Comment by Be-ing** [comment]
Already done in #461... please let's not make more merge conflicts.

**Comment by philburk** [comment]
> Already done in #461... please let's not make more merge conflicts.

Thanks for pointing out that this an alternative PR. If we cannot move forward on #461 then this may be a good option. It is smaller in scope and easier to accept.

**Comment by RossBencina** [comment]
@Be-ing please reconfirm that this was done in #461 and that we can now close it.

**Comment by h3ndrk** [comment]
@Be-ing implemented this, I will close my PR. Thanks for the CMake rewrite!

**Pull request closed without merging**
