### PR TITLE
test: check active and stopped states

### PR DESCRIPTION
**Pull request by philburk**
Query Pa_IsStreamActive() and Pa_IsStreamStopped()
and verify correct response.

### CODE REVIEW

**Comment by philburk** [comment]
This test is to help verify #678

**Comment by dmitrykos** [comment]
@philburk thank you for the test, I tried to run WASAPI against it and it failed due to a callback call after paComplete. The problem is probably outside #678 because `running` state variable is not participating in the scenario. 

There is possibility that buffer can be processed multiple times before hCloseRequest event is checked again. I am going to fix it and make test pass, then will comment in #678 regarding how we proceed further.

**Review by dmitrykos — COMMENTED** [review]
The `stream` variable has to be initialized to NULL to avoid failing on bad pointer access if test fails (faced this problem):

https://github.com/PortAudio/portaudio/blob/18f1d9d9ada6d02d508357b23a5b999fb3e8ee9f/test/patest_callbackstop.c#L153

**Comment by philburk** [comment]
Thanks Dmitry. I initialized stream to NULL.

**Comment by philburk** [comment]
__LINE__ used. Thanks.

**Comment by dmitrykos** [comment]
Phil, great! I pushed new #681 PR related to our discussion in #678. It passes this test successfully now.

**Comment by RossBencina** [comment]
For reference, there is a state machine diagram here that indicates the correct active/stopped values for each stream state:

http://www.portaudio.com/docs/proposals/010-ClarifyStreamStateMachine.html

**Review by RossBencina — APPROVED** [review]

**Pull request merged**
